mod asar;
mod error;
mod fs_utils;
mod frontend_locale;
mod frontend_patch;
mod hardcoded;
mod install;
mod logging;
mod menu_patch;
mod online_dom;
mod record;
mod resources;
mod restore;
mod skills;
mod types;

pub use asar::*;
pub use error::*;
pub use fs_utils::*;
pub use frontend_locale::*;
pub use frontend_patch::*;
pub use hardcoded::*;
pub use install::*;
pub use logging::*;
pub use menu_patch::*;
pub use online_dom::*;
pub use record::*;
pub use resources::*;
pub use restore::*;
pub use skills::*;
pub use types::*;

pub const ASAR_PATCH_TARGET: &str = ".vite/build/index.js";
